## 데이터 탐색 연습

1. 전체 주문 수
2. 구매자 수
3. 상품 별 주문 건수
4. 이용자 별 주문 수, 평균 주문 수
5. 가장 많이 판매되는 상품 랭킹
6. 카트에 첫 번째로 담기는 상품 랭킹
7. 시간 별 주문 건수
8. 첫 구매 후 다음 구매까지 걸린 평균 일수
9. 재주문율이 높은 상품
10. Department 별 재구매율이 높은 상품

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
orders = pd.read_csv('orders.csv')
orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [5]:
products = pd.read_csv('products.csv')
products

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13
...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5
49684,49685,En Croute Roast Hazelnut Cranberry,42,1
49685,49686,Artisan Baguette,112,3
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8
49687,49688,Fresh Foaming Cleanser,73,11

In [6]:
opp = pd.read_csv('order_products__prior.csv')

In [7]:
opp_m = pd.merge(opp, products, on='product_id', how='left' )

In [8]:
dpt = pd.read_csv('departments.csv')

In [9]:
opp_m2 = pd.merge(opp_m, dpt, on = 'department_id', how='left')
opp_m2

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department
0,2,33120,1,1,Organic Egg Whites,86,16,dairy eggs
1,2,28985,2,1,Michigan Organic Kale,83,4,produce
2,2,9327,3,0,Garlic Powder,104,13,pantry
3,2,45918,4,1,Coconut Butter,19,13,pantry
4,2,30035,5,0,Natural Sweetener,17,13,pantry
...,...,...,...,...,...,...,...,...
32434484,3421083,39678,6,1,Free & Clear Natural Dishwasher Detergent,74,17,household
32434485,3421083,11352,7,0,Organic Mini Sandwich Crackers Peanut Butter,78,19,snacks
32434486,3421083,4600,8,0,All Natural French Toast Sticks,52,1,frozen
32434487,3421083,24852,9,1,Banana,24,4,produce
32434488,3421083,5020,10,1,Organic Sweet & Salty Peanut Pretzel Granola ...,3,19,snacks

In [11]:
opt = pd.read_csv('order_products__train.csv')

In [12]:
# prior, train 합친 거

opp1 = opp.copy()
opt1 = opt.copy()
oppt = pd.concat([opp1, opt1])

oppt = oppt.reset_index(drop=True)

In [13]:
oppt_m = pd.merge(oppt, products, on='product_id', how='left' )

In [14]:
oppt_m2 = pd.merge(oppt_m, dpt, on = 'department_id', how='left')
oppt_m2

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department
0,2,33120,1,1,Organic Egg Whites,86,16,dairy eggs
1,2,28985,2,1,Michigan Organic Kale,83,4,produce
2,2,9327,3,0,Garlic Powder,104,13,pantry
3,2,45918,4,1,Coconut Butter,19,13,pantry
4,2,30035,5,0,Natural Sweetener,17,13,pantry
...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,Natural Artesian Water,115,7,beverages
33819102,3421063,35548,4,1,Twice Baked Potatoes,13,20,deli
33819103,3421070,35951,1,1,Organic Unsweetened Almond Milk,91,16,dairy eggs
33819104,3421070,16953,2,1,Creamy Peanut Butter,88,13,pantry
33819105,3421070,4724,3,1,Broccoli Florettes,32,4,produce

In [15]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

In [16]:
# 1. 전체 주문 수

orders['order_id'].nunique()

3421083

In [6]:
# 2. 구매자 수

orders['user_id'].nunique()

206209

In [35]:
# 3. 상품 별 주문 건수 (prior만)

opp.groupby('product_id')['order_id'].count()

product_id
1        1852
2          90
3         277
4         329
5          15
         ...
49684       9
49685      49
49686     120
49687      13
49688      89
Name: order_id, Length: 49677, dtype: int64

In [44]:
# 3-2. 상품 별 주문 건수 (두개 합친 거)

oppt.groupby('product_id')['order_id'].count()

product_id
1        1928
2          94
3         283
4         351
5          16
         ...
49684       9
49685      49
49686     127
49687      14
49688      93
Name: order_id, Length: 49685, dtype: int64

In [17]:
# 4-1. 이용자별 주문 수

orders.groupby('user_id')[['order_id']].count()

         order_id
user_id
1              11
2              15
3              13
4               6
5               5
...           ...
206205          4
206206         68
206207         17
206208         50
206209         14

[206209 rows x 1 columns]

In [19]:
#4-2. 이용자별 평균 주문 수

order_counts = orders.groupby('user_id')[['order_id']].count()

order_counts.mean()

order_id    16.590367
dtype: float64

In [30]:
# 번외) 주문자별 최소 주문 수

order_count_min = order_counts.min()
order_count_min

order_id    4
dtype: int64

In [23]:
# 5. 가장 많이 판매되는 상품 10위

# prior만

opp_m.groupby(['product_id','product_name'])['order_id'].count().sort_values(ascending=False).head(10)

product_id  product_name
24852       Banana                    472565
13176       Bag of Organic Bananas    379450
21137       Organic Strawberries      264683
21903       Organic Baby Spinach      241921
47209       Organic Hass Avocado      213584
47766       Organic Avocado           176815
47626       Large Lemon               152657
16797       Strawberries              142951
26209       Limes                     140627
27845       Organic Whole Milk        137905
Name: order_id, dtype: int64

In [24]:
# 두개 합친 거

oppt_m.groupby(['product_id','product_name'])['order_id'].count().sort_values(ascending=False).head(10)

product_id  product_name
24852       Banana                    491291
13176       Bag of Organic Bananas    394930
21137       Organic Strawberries      275577
21903       Organic Baby Spinach      251705
47209       Organic Hass Avocado      220877
47766       Organic Avocado           184224
47626       Large Lemon               160792
16797       Strawberries              149445
26209       Limes                     146660
27845       Organic Whole Milk        142813
Name: order_id, dtype: int64

In [30]:
# 6. 카트에 첫 번째로 담기는 상품 10개

first_cart = opp_m2[opp_m2['add_to_cart_order'] == 1]
first_cart.groupby

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department
0,2,33120,1,1,Organic Egg Whites,86,16,dairy eggs
9,3,33754,1,1,Total 2% with Strawberry Lowfat Greek Strained...,120,16,dairy eggs
17,4,46842,1,0,Plain Pre-Sliced Bagels,93,3,bakery
30,5,13176,1,1,Bag of Organic Bananas,24,4,produce
56,6,40462,1,0,Cleanse,31,7,beverages
...,...,...,...,...,...,...,...,...
32434455,3421079,30136,1,0,Moisture Soap,25,11,personal care
32434456,3421080,27845,1,1,Organic Whole Milk,84,16,dairy eggs
32434465,3421081,38185,1,0,Hint of Lime Flavored Tortilla Chips,107,19,snacks
32434472,3421082,17279,1,1,Fresh 99% Lean Ground Turkey,49,12,meat seafood
32434479,3421083,7854,1,0,Freeze Dried Mango Slices,117,19,snacks

In [25]:
#7. 시간별 주문 건수

orders_per_hour = orders.groupby('order_hour_of_day')['order_id'].count()

orders_per_hour.sort_values(ascending=False).head(10)

# => 오전, 오후 혹은 시간 블록으로 나눠보는 것도 좋을 거 같다

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
Name: order_id, dtype: int64

In [31]:
# 8. 첫 구매 후 다음 구매까지 걸린 평균 일수

orders['days_since_prior_order'].mean()

11.114836226863012

In [11]:
# 9. 재주문율이 높은 상품

# prior만

opp_m.groupby(['product_id', 'product_name'])['reordered'].count().sort_values(ascending=False).head(10)

product_id  product_name
24852       Banana                    472565
13176       Bag of Organic Bananas    379450
21137       Organic Strawberries      264683
21903       Organic Baby Spinach      241921
47209       Organic Hass Avocado      213584
47766       Organic Avocado           176815
47626       Large Lemon               152657
16797       Strawberries              142951
26209       Limes                     140627
27845       Organic Whole Milk        137905
Name: reordered, dtype: int64

In [17]:
# 두개 합친 거

oppt_m.groupby(['product_id', 'product_name'])['reordered'].count().sort_values(ascending=False).head(10)

product_id  product_name
24852       Banana                    491291
13176       Bag of Organic Bananas    394930
21137       Organic Strawberries      275577
21903       Organic Baby Spinach      251705
47209       Organic Hass Avocado      220877
47766       Organic Avocado           184224
47626       Large Lemon               160792
16797       Strawberries              149445
26209       Limes                     146660
27845       Organic Whole Milk        142813
Name: reordered, dtype: int64

In [19]:
# 10. Department 별 재구매율이 높은 상품


opp_m2.groupby(['department_id', 'product_name'])['reordered'].count().sort_values(ascending=False).head(10)

department_id  product_name
4              Banana                    472565
               Bag of Organic Bananas    379450
               Organic Strawberries      264683
               Organic Baby Spinach      241921
               Organic Hass Avocado      213584
               Organic Avocado           176815
               Large Lemon               152657
               Strawberries              142951
               Limes                     140627
16             Organic Whole Milk        137905
Name: reordered, dtype: int64